Upgrade backend to Next.js 15 (#360)

diff --git a/.github/workflows/check-codegen.yaml b/.github/workflows/check-codegen.yaml
--- a/.github/workflows/check-codegen.yaml
+++ b/.github/workflows/check-codegen.yaml
@@ -1,38 +1,30 @@
-name: Publish Docs
+name: Ensure up-to-date codegen
 
 on:
   push:
     branches:
+      - dev
+      - main
+  pull_request:
+    branches:
+      - dev
       - main
 
 jobs:
-  run:
+  check_codegen:
     runs-on: ubuntu-latest
-    env:
-      NEXT_PUBLIC_STACK_API_URL: http://localhost:8102
-      NEXT_PUBLIC_STACK_PROJECT_ID: internal
-      NEXT_PUBLIC_STACK_PUBLISHABLE_CLIENT_KEY: internal-project-publishable-client-key
-      STACK_SECRET_SERVER_KEY: internal-project-secret-server-key
-      STACK_SERVER_SECRET: 23-wuNpik0gIW4mruTz25rbIvhuuvZFrLOLtL7J4tyo
 
-      STACK_EMAIL_HOST: 127.0.0.1
-      STACK_EMAIL_PORT: 2500
-      STACK_EMAIL_USERNAME: test
-      STACK_EMAIL_PASSWORD: none
-      STACK_EMAIL_SENDER: noreply@test.com
-
-      STACK_DATABASE_CONNECTION_STRING: postgres://postgres:PASSWORD-PLACEHOLDER--uqfEC1hmmv@localhost:5432/stackframe
-      STACK_DIRECT_DATABASE_CONNECTION_STRING: postgres://postgres:PASSWORD-PLACEHOLDER--uqfEC1hmmv@localhost:5432/stackframe
-
-    permissions: write-all
+    strategy:
+      matrix:
+        node-version: [22.x]
 
     steps:
       - uses: actions/checkout@v3
 
-      - name: Setup Node.js v20
+      - name: Setup Node.js ${{ matrix.node-version }}
         uses: actions/setup-node@v3
         with:
-          node-version: 20
+          node-version: ${{ matrix.node-version }}
 
       - name: Setup pnpm
         uses: pnpm/action-setup@v3
@@ -75,10 +67,47 @@ jobs:
       - name: Build
         run: pnpm build
 
-      - name: Check API is valid
-        run: pnpm run fern check
+      - name: Store Quetzal API key in packages/stack/.env.local
+        run: echo "QUETZAL_API_KEY=${{ secrets.QUETZAL_API_KEY }}" > packages/stack/.env.local
 
-      - name: Publish Docs
-        env:
-          FERN_TOKEN: ${{ secrets.FERN_TOKEN }}
-        run: pnpm run fern generate --docs --log-level debug
+      - name: Run code gen
+        run: pnpm codegen
+      
+      - name: Check for uncommitted changes
+        run: |
+          if [[ -n $(git status --porcelain) ]]; then
+            echo "Error: There are uncommitted changes after build/lint/typecheck."
+            echo "Please commit all changes before pushing."
+            git status
+            exit 1
+          fi
+
+  
+  check_prisma_migrations:
+    runs-on: ubuntu-latest
+
+    strategy:
+      matrix:
+        node-version: [22.x]
+
+    steps:
+      - uses: actions/checkout@v3
+
+      - name: Setup Node.js ${{ matrix.node-version }}
+        uses: actions/setup-node@v3
+        with:
+          node-version: ${{ matrix.node-version }}
+
+      - name: Setup pnpm
+        uses: pnpm/action-setup@v3
+        with:
+            version: 9.1.2
+
+      - name: Install dependencies
+        run: pnpm install --frozen-lockfile
+      
+      - name: Start Postgres shadow DB
+        run: docker run -d --name postgres-prisma-diff-shadow -e POSTGRES_USER=postgres -e POSTGRES_PASSWORD=PLACEHOLDER-PASSWORD--dfaBC1hm1v -e POSTGRES_DB=postgres -p 5432:5432 postgres:latest
+      
+      - name: Check for differences in Prisma schema and migrations
+        run: pnpm run prisma migrate diff --from-migrations ./prisma/migrations --to-schema-datamodel ./prisma/schema.prisma --shadow-database-url postgres://postgres:PLACEHOLDER-PASSWORD--dfaBC1hm1v@localhost:5432/postgres --exit-code
