Fix

diff --git a/.github/workflows/lint-and-build.yaml b/.github/workflows/lint-and-build.yaml
--- a/.github/workflows/lint-and-build.yaml
+++ b/.github/workflows/lint-and-build.yaml
@@ -72,6 +72,21 @@ jobs:
       
       - name: Typecheck
         run: pnpm typecheck
+
+      - name: Store Quetzal API key in packages/stack/.env.local to prepare for code gen
+        run: echo "QUETZAL_API_KEY=${{ secrets.QUETZAL_API_KEY }}" > packages/stack/.env.local
+
+      - name: Run code gen  # so we can check for uncommitted changes afterwards; `build` doesn't regenerate some committed files, eg. Quetzal
+        run: pnpm codegen
+      
+      - name: Check for uncommitted changes
+        run: |
+          if [[ -n $(git status --porcelain) ]]; then
+            echo "Error: There are uncommitted changes after build/lint/typecheck."
+            echo "Please commit all changes before pushing."
+            git status
+            exit 1
+          fi
       
       - name: Check for uncommitted changes
         run: |
